{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: defaulting.webhook.karpenter.azure.com
  labels:
    {{- include "karpenter.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
webhooks:
  - name: defaulting.webhook.karpenter.azure.com
    admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: {{ include "karpenter.fullname" . }}
        namespace: {{ .Release.Namespace }}
        port: {{ .Values.webhook.port }}
    failurePolicy: Fail
    sideEffects: None
    rules:
      - apiGroups:
          - karpenter.azure.com
        apiVersions:
          - v1alpha2
        operations:
          - CREATE
          - UPDATE
        resources:
          - aksnodeclasses
          - aksnodeclasses/status
        scope: '*'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation.webhook.karpenter.azure.com
  labels:
    {{- include "karpenter.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
webhooks:
  - name: validation.webhook.karpenter.azure.com
    admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: {{ include "karpenter.fullname" . }}
        namespace: {{ .Release.Namespace }}
        port: {{ .Values.webhook.port }}
    failurePolicy: Fail
    sideEffects: None
    rules:
      - apiGroups:
          - karpenter.azure.com
        apiVersions:
          - v1alpha2
        operations:
          - CREATE
          - UPDATE
        resources:
          - aksnodeclasses
          - aksnodeclasses/status
        scope: '*'
{{- end }}
