name: CI
on:
  push:
    branches: [azure/poc]
  pull_request:
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/install-deps
    - run: make ci-non-test
